### ISSUE TITLE
CSS Selectors with classnames or ids not working as intended

### ISSUE THREAD

**Issue by Henrixounez** [jantimon/next-yak#244]
When using CSS Selectors targeting elements with IDs or Classnames the styling is not applied to them because the CSS file generated have IDs on the selectors.

## ❌ Not working example:
```tsx
import { styled } from "next-yak";

export default function HomePage() {
  return (
    <Container>
      <h1 className="title">Home Page</h1>
      <p id="description-1">This is the home page of the app.</p>
      <p className="description-2">Welcome to the home page of the app.</p>
    </Container>
  );
}

const Container = styled.div`
  background-color: red;
  padding: 20px;

  > h1.title {
    color: blue;
  }
  > p#description {
    color: green;
  }
  > .description-class {
    color: yellow;
  }
`;
```

### Result:
![image](https://github.com/user-attachments/assets/d978f0cd-3009-4a7a-9733-35fc8c0c8532)

```css
.page_Container__1R4Gr {
  background-color: red;
  padding: 20px;
  > h1.page_title__Ot_ls {
    color: blue;
  }
  > p#page_description__dhQ1n {
    color: green;
  }
  > .page_description-class__Hu6Tw {
    color: yellow;
  }
}
```

```html
<div class="page_Container__1R4Gr">
  <h1 class="title">
    Home Page
  </h1>
  <p id="description-1">
    This is the home page of the app.
  </p>
  <p class="description-2">
    Welcome to the home page of the app.
  </p>
</div>
```

**Comment by jantimon** [comment]
the issue is that Next.js's CSS Modules (which next-yak uses under the hood) is adding module-specific prefixes to all selectors and ids automatically

the `:global()` function allows to disable the postfix generation in CSS Modules:

## ✅ Working example:
```tsx
import { styled } from "next-yak";

export default function HomePage() {
  return (
    <Container>
      <h1 className="title">Home Page</h1>
      <p id="description-1">This is the home page of the app.</p>
      <p className="description-2">Welcome to the home page of the app.</p>
    </Container>
  );
}

const Container = styled.div`
  background-color: red;
  padding: 20px;
  
  /* Use :global() to target external class names */
  > h1:global(.title) {
    color: blue;
  }
  
  /* Use :global() for ID selectors */
  > p:global(#description-1) {
    color: green;
  }
  
  /* Use :global() for class selectors */
  > :global(.description-2) {
    color: yellow;
  }
`;
```

another way is targeting styled components directly:

import { styled } from "next-yak";

export default function HomePage() {
  return (
    <Container>
      <Title>Home Page</Title>
      <Description1>This is the home page of the app.</Description1>
      <Description2>Welcome to the home page of the app.</Description2>
    </Container>
  );
}

const Title = styled.h1`
`;

const Description1 = styled.p`
  margin: 1rem 0;
`;

const Description2 = styled.p`
  margin: 1rem 0;
`;

const Container = styled.div`
  background-color: red;
  padding: 20px;
  
  /* Target the Title component directly */
  ${Title} {
    color: blue;
  }
  
  /* Target the Description1 component directly */
  ${Description1} {
    color: green;
  }
  
  /* Target the Description2 component directly */
  ${Description2} {
    color: yellow;
  }
`;

**Comment by Henrixounez** [comment]
Thanks, that should work for my use case with the `:global()` applied around the selectors in the meantime even though that seems a bit verbose.
